name: ConnectionRe
main: ren.taske.connection.ConnectionPlugin
version: 1.2.0

commands:
  silent:
    description: Set if your word would be report to the QQ Group.
    usage: /silent OR /silent [true/false]
    permission: connection.silent
    permission-message: You don't have permission!